version: '3'
services:
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    volumes:
      - ./:/app