version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your-password
      MYSQL_DATABASE: your-dbname
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
